title: Rotaract 5040
email: your-email@example.com
description: >-
  An international network of students and young professionals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo_image: /assets/images/district_rotaract_logo.png
footer_logo: /assets/images/district_website_rotary_polio_logo_footer-1.png
footer_logo_alt: Rotary - End polio now

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  clubs:
    output: true  # We want a page for each club!

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
