title: Rotaract 5040
email: your-email@example.com
description: >-
  An international network of students and young professionals.
facebook_url: https://www.facebook.com/Rotaract5040/
instagram_url: https://www.instagram.com/rotaract5040/
district_email: drr@rotaract5040.org
logo_image: /assets/images/district_rotaract_logo.png
logo_image_mobile: /assets/images/rotoract_logo_mobile.png
footer_logo: /assets/images/district_website_rotary_polio_logo_footer-1.png
footer_logo_alt: Rotary - End polio now

# Build settings
markdown: CommonMarkGhPages

collections:
  clubs:
    output: true
  pace:
    output: true